INSERT INTO makers (name, name_eng, homepage_url, created_at, updated_at) VALUES
('스노우피크', 'Snow Peak', 'https://www.snowpeak.com', NOW(), NOW()),
('콜맨', 'Coleman', 'https://www.coleman.com', NOW(), NOW()),
('헬리녹스', 'Helinox', 'https://www.helinox.com', NOW(), NOW()),
('코베아', 'Kovea', 'https://www.kovea.com', NOW(), NOW()),
('카즈미', 'Kazmi', 'https://www.kazmi.co.kr', NOW(), NOW()),
('더노스페이스', 'The North Face', 'https://www.thenorthface.com', NOW(), NOW()),
('마모트', 'Marmot', 'https://www.marmot.com', NOW(), NOW()),
('오스프리', 'Osprey', 'https://www.osprey.com', NOW(), NOW()),
('그레고리', 'Gregory', 'https://www.gregorypacks.com', NOW(), NOW()),
('도이터', 'Deuter', 'https://www.deuter.com', NOW(), NOW()),
('MSR', 'MSR', 'https://www.msrgear.com', NOW(), NOW()),
('제트보일', 'Jetboil', 'https://www.jetboil.com', NOW(), NOW()),
('씨투서밋', 'Sea to Summit', 'https://www.seatosummit.com', NOW(), NOW()),
('써모레스트', 'Therm-a-Rest', 'https://www.thermarest.com', NOW(), NOW()),
('네모', 'Nemo', 'https://www.nemoequipment.com', NOW(), NOW()),
('빅애그니스', 'Big Agnes', 'https://www.bigagnes.com', NOW(), NOW()),
('켈티', 'Kelty', 'https://www.kelty.com', NOW(), NOW()),
('블랙다이아몬드', 'Black Diamond', 'https://www.blackdiamondequipment.com', NOW(), NOW()),
('페츨', 'Petzl', 'https://www.petzl.com', NOW(), NOW()),
('스탠리', 'Stanley', 'https://www.stanley1913.com', NOW(), NOW()),
('예티', 'YETI', 'https://www.yeti.com', NOW(), NOW()),
('이글루', 'Igloo', 'https://www.igloocoolers.com', NOW(), NOW()),
('도메틱', 'Dometic', 'https://www.dometic.com', NOW(), NOW()),
('하이드로플라스크', 'Hydro Flask', 'https://www.hydroflask.com', NOW(), NOW()),
('프리머스', 'Primus', 'https://www.primus.eu', NOW(), NOW()),
('트랜지아', 'Trangia', 'https://www.trangia.se', NOW(), NOW()),
('바이오라이트', 'BioLite', 'https://www.bioliteenergy.com', NOW(), NOW()),
('캠프쉐프', 'Camp Chef', 'https://www.campchef.com', NOW(), NOW()),
('GSI아웃도어스', 'GSI Outdoors', 'https://www.gsioutdoors.com', NOW(), NOW()),
('옵티머스', 'Optimus', 'https://www.optimusstoves.com', NOW(), NOW()),
('엑스페드', 'Exped', 'https://www.exped.com', NOW(), NOW()),
('네파', 'Nepa', 'https://www.nepa.co.kr', NOW(), NOW()),
('라푸마', 'Lafuma', 'https://www.lafuma.com', NOW(), NOW()),
('마운틴하드웨어', 'Mountain Hardwear', 'https://www.mountainhardwear.com', NOW(), NOW()),
('아크테릭스', 'Arc''teryx', 'https://www.arcteryx.com', NOW(), NOW()),
('파타고니아', 'Patagonia', 'https://www.patagonia.com', NOW(), NOW()),
('밀레', 'Millet', 'https://www.millet.fr', NOW(), NOW()),
('살레와', 'Salewa', 'https://www.salewa.com', NOW(), NOW()),
('마무트', 'Mammut', 'https://www.mammut.com', NOW(), NOW()),
('네이처하이크', 'Naturehike', 'https://www.naturehike.com', NOW(), NOW()),
('퀘차', 'Quechua', 'https://www.quechua.com', NOW(), NOW()),
('로고스', 'Logos', 'https://www.logos-brand.com', NOW(), NOW()),
('캡틴스타그', 'Captain Stag', 'https://www.captain-stag.com', NOW(), NOW()),
('유니플레임', 'Uniflame', 'https://www.uniflame.co.jp', NOW(), NOW()),
('소토', 'Soto', 'https://www.sotooutdoors.com', NOW(), NOW()),
('스노우라인', 'Snowline', 'https://www.snowline.co.kr', NOW(), NOW()),
('에버뉴', 'Evernew', 'https://www.evernew.co.jp', NOW(), NOW()),
('파이어메이플', 'Fire Maple', 'https://www.firemaplegear.com', NOW(), NOW()),
('아웃도어연구소', 'Outdoor Research', 'https://www.outdoorresearch.com', NOW(), NOW()),
('버팔로', 'Buffalo', 'https://www.buffalosystems.co.uk', NOW(), NOW()),
('마운틴스미스', 'Mountainsmith', 'https://www.mountainsmith.com', NOW(), NOW()),
('왕가텐트', 'Wangga Tent', NULL, NOW(), NOW()),
('캠핑문', 'Camping Moon', 'https://www.campingmoon.co.kr', NOW(), NOW()),
('아이언레이크', 'Iron Lake', NULL, NOW(), NOW()),
('에코라이프', 'Ecolife', NULL, NOW(), NOW()),
('필드앤마운틴', 'Field and Mountain', NULL, NOW(), NOW()),
('하이마운트', 'High Mount', NULL, NOW(), NOW()),
('팀버라인', 'Timberline', NULL, NOW(), NOW()),
('윈드리버', 'Wind River', NULL, NOW(), NOW()),
('해피아웃도어', 'Happy Outdoor', NULL, NOW(), NOW()),
('써클캠프', 'Circle Camp', NULL, NOW(), NOW()),
('피크세이버', 'Peak Saver', NULL, NOW(), NOW()),
('캠핑존', 'Camping Zone', NULL, NOW(), NOW()),
('그린캠프', 'Green Camp', NULL, NOW(), NOW()),
('이너텐트', 'Inner Tent', NULL, NOW(), NOW()),
('아이언월', 'Iron Wall', NULL, NOW(), NOW()),
('키슬링', 'Kiesling', NULL, NOW(), NOW()),
('텐트팩토리', 'Tent Factory', NULL, NOW(), NOW()),
('캠프타운', 'Camp Town', NULL, NOW(), NOW()),
('어스하이커', 'Earth Hiker', NULL, NOW(), NOW()),
('마운틴킹', 'Mountain King', NULL, NOW(), NOW()),
('와일드캠프', 'Wild Camp', NULL, NOW(), NOW()),
('포레스트', 'Forest', NULL, NOW(), NOW()),
('리지라인', 'Ridgeline', NULL, NOW(), NOW()),
('써밋서플라이', 'Summit Supply', NULL, NOW(), NOW()),
('캠프그라운드', 'Campground', NULL, NOW(), NOW()),
('노르딕아웃도어', 'Nordic Outdoor', NULL, NOW(), NOW()),
('알파인기어', 'Alpine Gear', NULL, NOW(), NOW()),
('트레일블레이저', 'Trailblazer', NULL, NOW(), NOW()),
('오버랜더', 'Overlander', NULL, NOW(), NOW()),
('베이스캠프', 'Basecamp', NULL, NOW(), NOW()),
('솔로캠퍼', 'Solo Camper', NULL, NOW(), NOW()),
('그루브캠프', 'Groove Camp', NULL, NOW(), NOW()),
('선라이즈아웃도어', 'Sunrise Outdoor', NULL, NOW(), NOW()),
('레이크사이드', 'Lakeside', NULL, NOW(), NOW()),
('리버사이드', 'Riverside', NULL, NOW(), NOW()),
('우드랜드', 'Woodland', NULL, NOW(), NOW()),
('스카이라인', 'Skyline', NULL, NOW(), NOW()),
('크레스트', 'Crest', NULL, NOW(), NOW()),
('버티컬', 'Vertical', NULL, NOW(), NOW()),
('캐년아웃도어', 'Canyon Outdoor', NULL, NOW(), NOW()),
('피크스', 'Peaks', NULL, NOW(), NOW()),
('스파이더', 'Spider', NULL, NOW(), NOW()),
('포레클라즈', 'Forclaz', NULL, NOW(), NOW()),
('바이어', 'Byer', NULL, NOW(), NOW()),
('줄보', 'Zulbo', NULL, NOW(), NOW()),
('레드독', 'Red Dog', NULL, NOW(), NOW()),
('팩타운', 'Packtowl', 'https://www.packtowl.com', NOW(), NOW()),
('REI', 'REI', 'https://www.rei.com', NOW(), NOW());
