export const REGION_OPTIONS = [
  { value: "SEOUL", label: "서울특별시" },
  { value: "BUSAN", label: "부산광역시" },
  { value: "DAEGU", label: "대구광역시" },
  { value: "INCHEON", label: "인천광역시" },
  { value: "GWANGJU", label: "광주광역시" },
  { value: "DAEJEON", label: "대전광역시" },
  { value: "ULSAN", label: "울산광역시" },
  { value: "SEJONG", label: "세종특별자치시" },
  { value: "GYEONGGI", label: "경기도" },
  { value: "GANGWON", label: "강원특별자치도" },
  { value: "CHUNGBUK", label: "충청북도" },
  { value: "CHUNGNAM", label: "충청남도" },
  { value: "JEONBUK", label: "전북특별자치도" },
  { value: "JEONNAM", label: "전라남도" },
  { value: "GYEONGBUK", label: "경상북도" },
  { value: "GYEONGNAM", label: "경상남도" },
  { value: "JEJU", label: "제주특별자치도" }
];

export const DISTRICT_MAP = {
  SEOUL: [
    { value: "SEOUL_JONGNO_GU", label: "종로구" },
    { value: "SEOUL_JUNG_GU", label: "중구" },
    { value: "SEOUL_YONGSAN_GU", label: "용산구" },
    { value: "SEOUL_SEONGDONG_GU", label: "성동구" },
    { value: "SEOUL_GWANGJIN_GU", label: "광진구" },
    { value: "SEOUL_DONGDAEMUN_GU", label: "동대문구" },
    { value: "SEOUL_JUNGNANG_GU", label: "중랑구" },
    { value: "SEOUL_SEONGBUK_GU", label: "성북구" },
    { value: "SEOUL_GANGBUK_GU", label: "강북구" },
    { value: "SEOUL_DOBONG_GU", label: "도봉구" },
    { value: "SEOUL_NOWON_GU", label: "노원구" },
    { value: "SEOUL_EUNPYEONG_GU", label: "은평구" },
    { value: "SEOUL_SEODAEMUN_GU", label: "서대문구" },
    { value: "SEOUL_MAPO_GU", label: "마포구" },
    { value: "SEOUL_YANGCHEON_GU", label: "양천구" },
    { value: "SEOUL_GANGSEO_GU", label: "강서구" },
    { value: "SEOUL_GURO_GU", label: "구로구" },
    { value: "SEOUL_GEUMCHEON_GU", label: "금천구" },
    { value: "SEOUL_YEONGDEUNGPO_GU", label: "영등포구" },
    { value: "SEOUL_DONGJAK_GU", label: "동작구" },
    { value: "SEOUL_GWANAK_GU", label: "관악구" },
    { value: "SEOUL_SEOCHO_GU", label: "서초구" },
    { value: "SEOUL_GANGNAM_GU", label: "강남구" },
    { value: "SEOUL_SONGPA_GU", label: "송파구" },
    { value: "SEOUL_GANGDONG_GU", label: "강동구" }
  ],
  BUSAN: [
    { value: "BUSAN_JUNG_GU", label: "중구" },
    { value: "BUSAN_SEO_GU", label: "서구" },
    { value: "BUSAN_DONG_GU", label: "동구" },
    { value: "BUSAN_YEONGDO_GU", label: "영도구" },
    { value: "BUSAN_BUSANJIN_GU", label: "부산진구" },
    { value: "BUSAN_DONGNAE_GU", label: "동래구" },
    { value: "BUSAN_NAM_GU", label: "남구" },
    { value: "BUSAN_BUK_GU", label: "북구" },
    { value: "BUSAN_HAEUNDAE_GU", label: "해운대구" },
    { value: "BUSAN_SAHA_GU", label: "사하구" },
    { value: "BUSAN_GEUMJEONG_GU", label: "금정구" },
    { value: "BUSAN_GANGSEO_GU", label: "강서구" },
    { value: "BUSAN_YEONJE_GU", label: "연제구" },
    { value: "BUSAN_SUYEONG_GU", label: "수영구" },
    { value: "BUSAN_SASANG_GU", label: "사상구" },
    { value: "BUSAN_GIJANG_GUN", label: "기장군" }
  ],
  DAEGU: [
    { value: "DAEGU_JUNG_GU", label: "중구" },
    { value: "DAEGU_DONG_GU", label: "동구" },
    { value: "DAEGU_SEO_GU", label: "서구" },
    { value: "DAEGU_NAM_GU", label: "남구" },
    { value: "DAEGU_BUK_GU", label: "북구" },
    { value: "DAEGU_SUSEONG_GU", label: "수성구" },
    { value: "DAEGU_DALSEO_GU", label: "달서구" },
    { value: "DAEGU_DALSEONG_GUN", label: "달성군" },
    { value: "DAEGU_GUNWI_GUN", label: "군위군" }
  ],
  INCHEON: [
    { value: "INCHEON_JUNG_GU", label: "중구" },
    { value: "INCHEON_DONG_GU", label: "동구" },
    { value: "INCHEON_MICHUHOL_GU", label: "미추홀구" },
    { value: "INCHEON_YEONSU_GU", label: "연수구" },
    { value: "INCHEON_NAMDONG_GU", label: "남동구" },
    { value: "INCHEON_BUPYEONG_GU", label: "부평구" },
    { value: "INCHEON_GYEYANG_GU", label: "계양구" },
    { value: "INCHEON_SEO_GU", label: "서구" },
    { value: "INCHEON_GANGHWA_GUN", label: "강화군" },
    { value: "INCHEON_ONGJIN_GUN", label: "옹진군" }
  ],
  GWANGJU: [
    { value: "GWANGJU_DONG_GU", label: "동구" },
    { value: "GWANGJU_SEO_GU", label: "서구" },
    { value: "GWANGJU_NAM_GU", label: "남구" },
    { value: "GWANGJU_BUK_GU", label: "북구" },
    { value: "GWANGJU_GWANGSAN_GU", label: "광산구" }
  ],
  DAEJEON: [
    { value: "DAEJEON_DONG_GU", label: "동구" },
    { value: "DAEJEON_JUNG_GU", label: "중구" },
    { value: "DAEJEON_SEO_GU", label: "서구" },
    { value: "DAEJEON_YUSEONG_GU", label: "유성구" },
    { value: "DAEJEON_DAEDEOK_GU", label: "대덕구" }
  ],
  ULSAN: [
    { value: "ULSAN_JUNG_GU", label: "중구" },
    { value: "ULSAN_NAM_GU", label: "남구" },
    { value: "ULSAN_DONG_GU", label: "동구" },
    { value: "ULSAN_BUK_GU", label: "북구" },
    { value: "ULSAN_ULJU_GUN", label: "울주군" }
  ],
  SEJONG: [
    { value: "SEJONG_SEJONG_SI", label: "세종시" }
  ],
  GYEONGGI: [
    { value: "GYEONGGI_SUWON_SI", label: "수원시" },
    { value: "GYEONGGI_SEONGNAM_SI", label: "성남시" },
    { value: "GYEONGGI_UIJEONGBU_SI", label: "의정부시" },
    { value: "GYEONGGI_ANYANG_SI", label: "안양시" },
    { value: "GYEONGGI_BUCHEON_SI", label: "부천시" },
    { value: "GYEONGGI_GWANGMYEONG_SI", label: "광명시" },
    { value: "GYEONGGI_PYEONGTAEK_SI", label: "평택시" },
    { value: "GYEONGGI_DONGDUCHEON_SI", label: "동두천시" },
    { value: "GYEONGGI_ANSAN_SI", label: "안산시" },
    { value: "GYEONGGI_GOYANG_SI", label: "고양시" },
    { value: "GYEONGGI_GWACHEON_SI", label: "과천시" },
    { value: "GYEONGGI_GURI_SI", label: "구리시" },
    { value: "GYEONGGI_NAMYANGJU_SI", label: "남양주시" },
    { value: "GYEONGGI_OSAN_SI", label: "오산시" },
    { value: "GYEONGGI_SIHEUNG_SI", label: "시흥시" },
    { value: "GYEONGGI_GUNPO_SI", label: "군포시" },
    { value: "GYEONGGI_UIWANG_SI", label: "의왕시" },
    { value: "GYEONGGI_HANAM_SI", label: "하남시" },
    { value: "GYEONGGI_YONGIN_SI", label: "용인시" },
    { value: "GYEONGGI_PAJU_SI", label: "파주시" },
    { value: "GYEONGGI_ICHEON_SI", label: "이천시" },
    { value: "GYEONGGI_ANSEONG_SI", label: "안성시" },
    { value: "GYEONGGI_GIMPO_SI", label: "김포시" },
    { value: "GYEONGGI_HWASEONG_SI", label: "화성시" },
    { value: "GYEONGGI_GWANGJU_SI", label: "광주시" },
    { value: "GYEONGGI_YANGJU_SI", label: "양주시" },
    { value: "GYEONGGI_POCHEON_SI", label: "포천시" },
    { value: "GYEONGGI_YEOJU_SI", label: "여주시" },
    { value: "GYEONGGI_YEONCHEON_GUN", label: "연천군" },
    { value: "GYEONGGI_GAPYEONG_GUN", label: "가평군" },
    { value: "GYEONGGI_YANGPYEONG_GUN", label: "양평군" }
  ],
  GANGWON: [
    { value: "GANGWON_CHUNCHEON_SI", label: "춘천시" },
    { value: "GANGWON_WONJU_SI", label: "원주시" },
    { value: "GANGWON_GANGNEUNG_SI", label: "강릉시" },
    { value: "GANGWON_DONGHAE_SI", label: "동해시" },
    { value: "GANGWON_TAEBAEK_SI", label: "태백시" },
    { value: "GANGWON_SOKCHO_SI", label: "속초시" },
    { value: "GANGWON_SAMCHEOK_SI", label: "삼척시" },
    { value: "GANGWON_HONGCHEON_GUN", label: "홍천군" },
    { value: "GANGWON_HOENGSEONG_GUN", label: "횡성군" },
    { value: "GANGWON_YEONGWOL_GUN", label: "영월군" },
    { value: "GANGWON_PYEONGCHANG_GUN", label: "평창군" },
    { value: "GANGWON_JEONGSEON_GUN", label: "정선군" },
    { value: "GANGWON_CHEORWON_GUN", label: "철원군" },
    { value: "GANGWON_HWACHEON_GUN", label: "화천군" },
    { value: "GANGWON_YANGGU_GUN", label: "양구군" },
    { value: "GANGWON_INJE_GUN", label: "인제군" },
    { value: "GANGWON_GOSEONG_GUN", label: "고성군" },
    { value: "GANGWON_YANGYANG_GUN", label: "양양군" }
  ],
  CHUNGBUK: [
    { value: "CHUNGBUK_CHEONGJU_SI", label: "청주시" },
    { value: "CHUNGBUK_CHUNGJU_SI", label: "충주시" },
    { value: "CHUNGBUK_JECHEON_SI", label: "제천시" },
    { value: "CHUNGBUK_BOEUN_GUN", label: "보은군" },
    { value: "CHUNGBUK_OKCHEON_GUN", label: "옥천군" },
    { value: "CHUNGBUK_YEONGDONG_GUN", label: "영동군" },
    { value: "CHUNGBUK_JEUNGPYEONG_GUN", label: "증평군" },
    { value: "CHUNGBUK_JINCHEON_GUN", label: "진천군" },
    { value: "CHUNGBUK_GOESAN_GUN", label: "괴산군" },
    { value: "CHUNGBUK_EUMSEONG_GUN", label: "음성군" },
    { value: "CHUNGBUK_DANYANG_GUN", label: "단양군" }
  ],
  CHUNGNAM: [
    { value: "CHUNGNAM_CHEONAN_SI", label: "천안시" },
    { value: "CHUNGNAM_GONGJU_SI", label: "공주시" },
    { value: "CHUNGNAM_BORYEONG_SI", label: "보령시" },
    { value: "CHUNGNAM_ASAN_SI", label: "아산시" },
    { value: "CHUNGNAM_SEOSAN_SI", label: "서산시" },
    { value: "CHUNGNAM_NONSAN_SI", label: "논산시" },
    { value: "CHUNGNAM_GYERYONG_SI", label: "계룡시" },
    { value: "CHUNGNAM_DANGJIN_SI", label: "당진시" },
    { value: "CHUNGNAM_GEUMSAN_GUN", label: "금산군" },
    { value: "CHUNGNAM_BUYEO_GUN", label: "부여군" },
    { value: "CHUNGNAM_SEOCHEON_GUN", label: "서천군" },
    { value: "CHUNGNAM_CHEONGYANG_GUN", label: "청양군" },
    { value: "CHUNGNAM_HONGSEONG_GUN", label: "홍성군" },
    { value: "CHUNGNAM_YESAN_GUN", label: "예산군" },
    { value: "CHUNGNAM_TAEAN_GUN", label: "태안군" }
  ],
  JEONBUK: [
    { value: "JEONBUK_JEONJU_SI", label: "전주시" },
    { value: "JEONBUK_GUNSAN_SI", label: "군산시" },
    { value: "JEONBUK_IKSAN_SI", label: "익산시" },
    { value: "JEONBUK_JEONGEUP_SI", label: "정읍시" },
    { value: "JEONBUK_NAMWON_SI", label: "남원시" },
    { value: "JEONBUK_GIMJE_SI", label: "김제시" },
    { value: "JEONBUK_WANJU_GUN", label: "완주군" },
    { value: "JEONBUK_JINAN_GUN", label: "진안군" },
    { value: "JEONBUK_MUJU_GUN", label: "무주군" },
    { value: "JEONBUK_JANGSU_GUN", label: "장수군" },
    { value: "JEONBUK_IMSIL_GUN", label: "임실군" },
    { value: "JEONBUK_SUNCHANG_GUN", label: "순창군" },
    { value: "JEONBUK_GOCHANG_GUN", label: "고창군" },
    { value: "JEONBUK_BUAN_GUN", label: "부안군" }
  ],
  JEONNAM: [
    { value: "JEONNAM_MOKPO_SI", label: "목포시" },
    { value: "JEONNAM_YEOSU_SI", label: "여수시" },
    { value: "JEONNAM_SUNCHEON_SI", label: "순천시" },
    { value: "JEONNAM_NAJU_SI", label: "나주시" },
    { value: "JEONNAM_GWANGYANG_SI", label: "광양시" },
    { value: "JEONNAM_DAMYANG_GUN", label: "담양군" },
    { value: "JEONNAM_GOKSEONG_GUN", label: "곡성군" },
    { value: "JEONNAM_GURYE_GUN", label: "구례군" },
    { value: "JEONNAM_GOHEUNG_GUN", label: "고흥군" },
    { value: "JEONNAM_BOSEONG_GUN", label: "보성군" },
    { value: "JEONNAM_HWASUN_GUN", label: "화순군" },
    { value: "JEONNAM_JANGHEUNG_GUN", label: "장흥군" },
    { value: "JEONNAM_GANGJIN_GUN", label: "강진군" },
    { value: "JEONNAM_HAENAM_GUN", label: "해남군" },
    { value: "JEONNAM_YEONGAM_GUN", label: "영암군" },
    { value: "JEONNAM_MUAN_GUN", label: "무안군" },
    { value: "JEONNAM_HAMPYEONG_GUN", label: "함평군" },
    { value: "JEONNAM_YEONGGWANG_GUN", label: "영광군" },
    { value: "JEONNAM_JANGSEONG_GUN", label: "장성군" },
    { value: "JEONNAM_WANDO_GUN", label: "완도군" },
    { value: "JEONNAM_JINDO_GUN", label: "진도군" },
    { value: "JEONNAM_SINAN_GUN", label: "신안군" }
  ],
  GYEONGBUK: [
    { value: "GYEONGBUK_POHANG_SI", label: "포항시" },
    { value: "GYEONGBUK_GYEONGJU_SI", label: "경주시" },
    { value: "GYEONGBUK_GIMCHEON_SI", label: "김천시" },
    { value: "GYEONGBUK_ANDONG_SI", label: "안동시" },
    { value: "GYEONGBUK_GUMI_SI", label: "구미시" },
    { value: "GYEONGBUK_YEONGJU_SI", label: "영주시" },
    { value: "GYEONGBUK_YEONGCHEON_SI", label: "영천시" },
    { value: "GYEONGBUK_SANGJU_SI", label: "상주시" },
    { value: "GYEONGBUK_MUNGYEONG_SI", label: "문경시" },
    { value: "GYEONGBUK_GYEONGSAN_SI", label: "경산시" },
    { value: "GYEONGBUK_UISEONG_GUN", label: "의성군" },
    { value: "GYEONGBUK_CHEONGSONG_GUN", label: "청송군" },
    { value: "GYEONGBUK_YEONGYANG_GUN", label: "영양군" },
    { value: "GYEONGBUK_YEONGDEOK_GUN", label: "영덕군" },
    { value: "GYEONGBUK_CHEONGDO_GUN", label: "청도군" },
    { value: "GYEONGBUK_GORYEONG_GUN", label: "고령군" },
    { value: "GYEONGBUK_SEONGJU_GUN", label: "성주군" },
    { value: "GYEONGBUK_CHILGOK_GUN", label: "칠곡군" },
    { value: "GYEONGBUK_YECHEON_GUN", label: "예천군" },
    { value: "GYEONGBUK_BONGHWA_GUN", label: "봉화군" },
    { value: "GYEONGBUK_ULJIN_GUN", label: "울진군" },
    { value: "GYEONGBUK_ULLEUNG_GUN", label: "울릉군" }
  ],
  GYEONGNAM: [
    { value: "GYEONGNAM_CHANGWON_SI", label: "창원시" },
    { value: "GYEONGNAM_JINJU_SI", label: "진주시" },
    { value: "GYEONGNAM_TONGYEONG_SI", label: "통영시" },
    { value: "GYEONGNAM_SACHEON_SI", label: "사천시" },
    { value: "GYEONGNAM_GIMHAE_SI", label: "김해시" },
    { value: "GYEONGNAM_MIRYANG_SI", label: "밀양시" },
    { value: "GYEONGNAM_GEOJE_SI", label: "거제시" },
    { value: "GYEONGNAM_YANGSAN_SI", label: "양산시" },
    { value: "GYEONGNAM_UIRYEONG_GUN", label: "의령군" },
    { value: "GYEONGNAM_HAMAN_GUN", label: "함안군" },
    { value: "GYEONGNAM_CHANGNYEONG_GUN", label: "창녕군" },
    { value: "GYEONGNAM_GOSEONG_GUN", label: "고성군" },
    { value: "GYEONGNAM_NAMHAE_GUN", label: "남해군" },
    { value: "GYEONGNAM_HADONG_GUN", label: "하동군" },
    { value: "GYEONGNAM_SANCHEONG_GUN", label: "산청군" },
    { value: "GYEONGNAM_HAMYANG_GUN", label: "함양군" },
    { value: "GYEONGNAM_GEOCHANG_GUN", label: "거창군" },
    { value: "GYEONGNAM_HAPCHEON_GUN", label: "합천군" }
  ],
  JEJU: [
    { value: "JEJU_JEJU_SI", label: "제주시" },
    { value: "JEJU_SEOGWIPO_SI", label: "서귀포시" }
  ]
};

export function getRegionLabel(regionCode) {
  return REGION_OPTIONS.find((r) => r.value === regionCode)?.label ?? regionCode;
}

export function getDistrictLabel(regionCode, districtCode) {
  return DISTRICT_MAP[regionCode]?.find((d) => d.value === districtCode)?.label ?? districtCode;
}
